# Docker Compose 파일 버전 3을 사용하고 있음을 나타냅니다.
version: "3"
# 이 부분은 정의하고자 하는 서비스들을 정의하는 곳입니다
services:
  # 서비스 이름으로, MySQL 데이터베이스를 가리킵니다.
  database:
    # mysql:8.0: 데이터베이스 서비스가 사용할 도커 이미지를 명시합니다. 이 경우 MySQL 버전 8.0을 사용합니다.
    image: mysql:8.0
    # MySQL 데이터베이스 서비스에서 사용할 환경 변수를 설정합니다.
    environment:
      # MYSQL_DATABASE는 데이터베이스 이름을, MYSQL_ROOT_HOST는 모든 호스트에서 root 계정에 접속 가능하도록 설정합니다.
      # MYSQL_ROOT_PASSWORD는 root 계정의 비밀번호를 설정하고, TZ는 타임존을 설정합니다.
      MYSQL_DATABASE: place
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root팅
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    # 컨테이너와 호스트 간에 공유할 볼륨을 설정합니다. 이 경우에는 MySQL 데이터베이스 데이터를 호스트의 ./db/data 경로에 저장합니다.
    volumes:
      - ./db/data:/var/lib/mysql
    # 호스트와 컨테이너 간의 포트 매핑을 설정합니다. 이 경우 호스트의 3306 포트를 MySQL 컨테이너의 3306 포트에 매핑합니다.
    ports:
      - 3308:3306
    # 항상 재시작합니다.
    restart: always